# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
on:
  push:
    paths: ["**.[rR]", "**.[qrR]md", "**.[rR]markdown", "**.[rR]nw"]

name: Style & Document

permissions:
  contents: write

jobs:
  document-and-style:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::roxygen2, any::styler
          needs: roxygen2, styler

      - name: Style code
        run: styler::style_pkg()
        shell: Rscript {0}

      - name: Generate documentation
        run: roxygen2::roxygenise()
        shell: Rscript {0}

      - name: Commit and push all changes
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add .
          git commit -m "Run styler & update documentation" || echo "No changes to commit"
          git pull --ff-only
          git push origin
